/**
 * @typedef {Object} PixpediaBreadcumbInterface
 * @property {String|null} name The item's name
 * @property {Number|null} position The item's position number
 */

/**
 * Get a breadcrumb interface
 * @param {Element} item
 * @returns {PixpediaBreadcumbInterface}
 */
const generate_breadcumb_interface = item => ({
    name: item.querySelector('*[itemprop="name"]').textContent,
    position: parseInt(item.querySelector('*[itemprop="position"]').content, 10)
});

/**
 * document, document, document
 * @param {Document} document The document element API.
 * @returns {PixpediaBreadcumbInterface[]}
 */
const generate_from_document = (document = Document) => {
    const list = document.querySelectorAll(`*[itemtype="http://schema.org/BreadcrumbList"] *[itemprop="itemListElement"]`);
    return [...list].map( generate_breadcumb_interface );
};

/**
 * The main function
 * @param {PageStatusInterface} status Status from `PageStatusInterface` generated by `PageStatus` class.
 * @param {Document} document The document element API.
 * @returns {PixpediaBreadcumbInterface[]}
 */
export const main = (status = { message: "document-uninitialised" }, document = Document) => {
    /**
     * @type {PixpediaBreadcumbInterface[]}
     */
    const empty = [{ name: null, position: null }];
    if( status.message === "normal" ) {
        return generate_from_document( document );
    }
    return empty;
};
